/**
 * SwaggerDemo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneDto } from './phoneDto';


/**
 * A person entry in the phone book
 */
export interface PersonDto { 
    /**
     * The unique identifier of the person
     */
    id?: number;
    /**
     * First name (given name)
     */
    firstName?: string | null;
    /**
     * Last name
     */
    lastName?: string | null;
    /**
     * Birth date
     */
    birthDate?: string | null;
    /**
     * The phones of this person
     */
    phones?: Array<PhoneDto> | null;
}

