/**
 * SwaggerDemo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A phone entry in phone book
 */
export interface PhoneDto { 
    /**
     * The number of phone entry in the person\'s phone entries
     */
    entryId?: number;
    /**
     * The label of the phone (main, home, office etc etc)
     */
    phoneLabel?: string | null;
    /**
     * The phone number
     */
    phoneNumber?: string | null;
}

